expected_output = {
    'list_of_neighbors': ['3ffe:201:1::1'],
    'neighbor': {
        '3ffe:201:1::1': {
            'address_family': {
                'VPNv4 Unicast': {
                    'accepted_prefixes': 0,
                    'announced_prefixes': 0,
                    'attribute_discard_prefixes': 0,
                    'community_attribute_sent': '(both)',
                    'index': 1,
                    'mask': '0x2',
                    'offset': 0,
                    'threat_as_withdraw_prefixes': 0,
                },
                'VPNv6 Unicast': {
                    'accepted_prefixes': 0,
                    'announced_prefixes': 0,
                    'attribute_discard_prefixes': 0,
                    'community_attribute_sent': '(both)',
                    'index': 1,
                    'mask': '0x2',
                    'offset': 0,
                    'threat_as_withdraw_prefixes': 0,
                },
            },
            'bgp_version': 4,
            'connections_dropped': 1,
            'connections_established': 1,
            'hold_time': 180,
            'keepalive_interval': 60,
            'last_reset': [
                'Mon Dec 12 13:28:20 2022',
                'due to Notification sent (Neighbor shutdown) at Established',
            ],
            'last_reset_at_established': [
                'Mon Dec 12 13:28:20 2022',
                'due to Notification sent (Neighbor shutdown) at Established',
            ],
            'link': 'internal',
            'local_as': '65000',
            'maximum_routes_per_interval': 10000,
            'md5': 'disable',
            'minimum_time_between_advertisement': 0,
            'read_thread': 'off',
            'received': 9933,
            'received_in_queue': 0,
            'received_notifications': 0,
            'remote_as': '65000',
            'route_refresh_request_received': 0,
            'route_refresh_request_sent': 0,
            'router_id': '0.0.0.0',
            'sent': 9935,
            'sent_in_queue': 0,
            'sent_notifications': 1,
            'session_state': 'Idle',
            'shutdown': True,
            'surveillance_nexthop_check': 'inactive',
            'surveillance_peer': 'inactive',
            'track': 'inactive',
            'update_source': 'Loopback1',
            'write_thread': 'off',
        }
    },
}
