#!/bin/bash

<< COMMENTOUT

    - マニュアル https://docs.github.com/ja/repositories/creating-and-managing-repositories/duplicating-a-repository

    - githubのリポジトリのベアクローンを作成する
        - cd ~/git/mirror/
        - git clone --mirror https://github.com/takamitsu-iida/pyats-fitelnet.git

    - azure devops側で新規にリポジトリを作成してURLをコピー

    - set-urlする
        - cd pyats-fitelnet.git
        - git remote set-url --push origin https://srv6@dev.azure.com/srv6/JP-SRv6-%E6%96%B0%E6%8A%80%E8%A1%93%E8%82%B2%E6%88%90_ADO/_git/pyats-fitelnet

    - 変更した場合はfetchして最新化してからpushする
        - cd ~/git/mirror/pyats-fitelnet.git
        - git fetch -p origin
        - git push --mirror

COMMENTOUT

cd ~/git/mirror/pyats-fitelnet.git; git fetch -p origin
cd ~/git/mirror/pyats-fitelnet.git; git push --mirror
