#!/bin/bash

SCRIPT_DIR=$(cd $(dirname $0); pwd)
JOB=$SCRIPT_DIR/job.py
TESTBED=$SCRIPT_DIR/../testbed.yaml
MOCK=$SCRIPT_DIR/mock.yaml

# RECORD
# pyats run job $JOB --testbed-file $TESTBED --record record

# REPLAY
# pyats run job $JOB --testbed-file $TESTBED --replay record

# REAL DEVICE
# pyats run job $JOB --testbed-file $TESTBED

# MOCK DEVICE$
pyats run job $JOB --testbed-file $MOCK
