#!/bin/bash

SCRIPT_DIR=$(cd $(dirname $0); pwd)

TESTBED=${SCRIPT_DIR}/testbed.yaml

ALL_SCRIPTS="
${SCRIPT_DIR}/check_interface_status/run
${SCRIPT_DIR}/check_ping_ce/run
${SCRIPT_DIR}/check_ping_core/run
${SCRIPT_DIR}/check_segment_list/run
${SCRIPT_DIR}/check_segment_list/run
"

# SCRIPTS=${ALL_SCRIPTS}

SCRIPTS="
${SCRIPT_DIR}/check_interface_status/test.py
"

DEVICES="f220-p fx201-p fx201-pe1 f220-pe2 f221-ce1 f221-ce2"

for script in ${SCRIPTS}; do
    dir=$(cd $(dirname ${script}); pwd)

    # --record付きで実行
    /usr/bin/env python ${script} --testbed ${TESTBED} --record ${dir}/record --allow-repeated-commands

    for device in ${DEVICES} ; do
        if [ -e ${dir}/record/${device} ] ; then
            /usr/bin/env python -m unicon.playback.mock --recorded-data ${dir}/record/${device} --output ${dir}/mock/${device}/mock_device.yaml
            sed --in-place "s/prompt: switch/prompt: $device/g" ${dir}/mock/${device}/mock_device.yaml
        fi
    done

done
