#!/bin/bash

SCRIPT_DIR=$(cd $(dirname $0); pwd)
JOB=$SCRIPT_DIR/job.py
TESTBED_REAL=$SCRIPT_DIR/../testbed.yaml
TESTBED_MOCK=$SCRIPT_DIR/../mock.yaml

while getopts cpm option; do
    case $option in
        c)
            echo "record job"
            pyats run job $JOB --testbed-file $TESTBED_REAL --record record
            exit
            ;;
        p)
            echo "replay job"
            pyats run job $JOB --testbed-file $TESTBED_REAL --replay record
            exit
            ;;
        m)
            # --mock_data_dirで渡した文字列はテストベッドの中の変数に置換される
            # テストベッド mock.yaml のこの部分
            # command: mock_device_cli --os fitelnet --mock_data_dir %CLI{mock_data_dir}/f221-ce2 --state connect
            echo "run using mock devices"
            pyats run job $JOB --testbed-file $TESTBED_MOCK --mock_data_dir $SCRIPT_DIR/mock
            exit
            ;;
        \?)
            echo "unknown option"
            exit
            ;;
    esac
done

pyats run job $JOB --testbed-file $TESTBED_REAL